export enum AppRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  RESTAURANT_OWNER = 'RESTAURANT_OWNER',
  RESTAURANT_MANAGER = 'RESTAURANT_MANAGER',
  RESTAURANT_STAFF = 'RESTAURANT_STAFF',
}

export const ROLES_KEY = 'roles';
